import { Button } from "@/components/ui/button"
import { Link } from "react-router-dom"
import { DatasetSelector } from "@/components/dataset_selector"
import { useDataset } from "@/DatasetContext"

// CONSTANTS
const KRONE_DESC = "Scalable and Interactive LLM-empowered Log Anomaly Detection";
const DEMO_NOTICE =
    "To ensure responsiveness and reproducibility, the demo visualizes precomputed outputs generated by the KRONE system.";

//Hero Component
export const HeroSection = () => {
    const { info } = useDataset();

    return (
        <section
            id="hero"
            className="relative flex flex-col min-h-[90vh] items-center justify-center px-4"
        >
            <div className="relative text-center flex flex-col items-center">
                {/* KRONE INTRODUCTION BLOCK */}
                <div className="inline-block relative animate-slide-in-left">
                    <div className="absolute inset-0 translate-x-2.5 translate-y-2.5 bg-white/90 z-0"></div>
                    <div className="relative bg-WPIRed px-10 py-7 md:px-14 md:py-8 z-10 shadow-[0_18px_48px_rgba(0,0,0,0.45)]">
                        <h1 className="text-5xl md:text-7xl font-WPIfont font-extrabold tracking-tight text-white text-balance">
                            <span>Introducing</span>
                            <span className="ml-4">Krone</span>
                        </h1>
                    </div>
                </div>

                {/* BRIEF KRONE DESC */}
                <p className="mt-10 max-w-3xl text-2xl md:text-3xl font-WPIfont font-semibold leading-snug text-white text-balance animate-slide-in-right">
                    {KRONE_DESC}
                </p>

                {/* DATASET PICKER + TEST BUTTON */}
                <div className="pt-9 animate-slide-in-bot">
                    <DatasetSelector className="mb-6" />

                    <Link to="/visualize-tree">
                        <Button
                            size="lg"
                            className="h-auto text-lg md:text-xl font-WPIfont font-semibold px-10 py-5 rounded-[10px]
                                       shadow-[0_10px_30px_rgba(0,0,0,0.38)]
                                       transition-transform duration-200 hover:-translate-y-0.5
                                       focus-visible:ring-4 focus-visible:ring-white/70 focus-visible:ring-offset-0"
                        >
                            {`Try Out KRONE (${info.label} dataset)`}
                        </Button>
                    </Link>
                </div>

                <p className="mt-6 max-w-xl px-6 font-WPIfont text-sm leading-relaxed text-white/80 animate-slide-in-bot">
                    {DEMO_NOTICE}
                </p>
            </div>
        </section>
    );
};
